### PR TITLE
Be with ESM and Vite 5+

### PR DESCRIPTION
**Pull request by hmsk**

### CODE REVIEW

**Comment by Stanzilla** [comment]
@hmsk looking forward to this! is there a npm publish that we can test?

**Comment by hmsk** [comment]
@Stanzilla Thanks for your interest! This has been out as `3.0.0-beta.x` https://github.com/hmsk/vite-plugin-markdown/releases/tag/v3.0.0-1
I'm glad to hear how your test goes :)

**Comment by Beraliv** [comment]
@hmsk I'm testing it on my website - https://github.com/Beraliv/beraliv.dev/pull/667 and it works perfectly! Do you need any help with it?

**Comment by hmsk** [comment]
@Beraliv Thanks for reporting. Your comment was the most helpful one to let me move forward.

**Pull request merged**
