### PR TITLE
Remove React markdown div wrapper.

### PR DESCRIPTION
**Pull request by sanny-io**
We can use fragments instead.

### CODE REVIEW

**Comment by hmsk** [comment]
Thanks for sending a PR! This will be a breaking change (The root div is intended to provide a single root consistently)
Is there any problem in your end by having `<div>`?

**Comment by sanny-io** [comment]
The div interferes with child selectors. Is there currently a way to set `className` for the div?

**Comment by hmsk** [comment]
I'd love to hear more!

> The div interferes with child selectors

could you elaborate the actual troublesome situation for instance?

> Is there currently a way to set className for the div?

no, but this approach should be appropriate, rather than getting rid of the root I think atm.

**Comment by sanny-io** [comment]
```css
.markdown > p {
  /* ... */
}
```

This rule does not work because there is a div wrapping the markdown. The div would have to be removed, given the `markdown` class, or the rule edited. I figured removing it was the easiest option, but I wasn't aware this would break anything. Some way to add classes would be good, but what breaks as a result of using fragments? Is there something I can fix?

**Comment by hmsk** [comment]
In that case, I think there are many workarounds (e.g. don't use `>` and scope the selector).

The change is just a "breaking change" as an npm module. If any implementation which uses this lib and expects `div` is a root element, may get unintentional breaking. this sounds really conservative for you since It's should not be a serious problem but I'd like to consider more about use-cases before making a "major" version update.

I appreciate your PR and feedback definitely. And mostly leaning toward getting rid of the `div` 😉

**Pull request closed without merging**
